### ISSUE TITLE
Write a 1-2 sentence summary of the presence we are creating

### ISSUE THREAD

**Issue by kdflint** [NorthBridge/smm-community#10]
Are we doing social justice commentary? Education about nonprofit technology? Event promotion? Membership marketing? 

Maybe all those things but let's try to narrow down in some reasonable way.

**Comment by kdflint** [comment]
Create a presence that demonstrates our authentic concern for social justice, especially as it relates to the work of our members. Demonstrate the importance and effectiveness of our work to bring technology resources to the sector through our membership benefits.

**Comment by kdflint** [comment]
@visionary920 - your thoughts on the above, just as a general directional kind of statement?

**Comment by visionary920** [comment]
How do you feel the word "authentic" will resonate with the target audience/readers versus a synonym such as genuine?

The core messaging is spot on. When we spoke like week, I believe we were both in agreement that the messaging should probably be a combination of the questions initially posed here. By having the summary, I can create a stronger list of ideas for SM posting.

Great job!

**Comment by kdflint** [comment]
I like the word "genuine" - will substitute.

https://docs.google.com/document/d/14ZNF9nxERcZgksRDshFwxW1fzcE9dwKjhUpcUFGFjjU/edit
