### ISSUE TITLE
Determine calendar for sm posting

### ISSUE THREAD

**Issue by kdflint** [NorthBridge/smm-community#7]
Similar to the sample calendar Cristina circulated.

**Comment by visionary920** [comment]
Research suggest a minimum of three (3) posts a week on Facebook. Content is key but you don't want to be inundated on "post days" with a lengthy message that may or may not resonate with readers. Here are ideas that allow for variety.

1) Show off expertise with a helpful tip
2) Share an attention-grabbing statistic
3) Share a member's post
4) Ask people to join email distribution list
5) Correct a common misconception that relates to the industry
6) Give a shout out to another local business or organization
7) Feature a member (Side note: Member of the month - This can be done at the very beginning or end of the month.)
8) Ask a multiple choice question
9) Share [something about] a community event that you're looking forward to
10) Share highlights from the community event
11) Share something funny - memes are a big hit especially with millennials
12) Share your latest email announcement or newsletter - this drives traffic to website
13) Post something in celebration of a milestone for NTA
14) Post something seasonal (e.g. holidays, season change)
15) Link to an infographic you think the audience will enjoy
16) Share some inspiration be it a quote, image, short story
17) Share your latest read - bonus if it's industry related
18) Introduce your newest employee or volunteer 
19) Create a video (series?) with a catchy title where it's either just you talking or dialogue between you and others such as a roundtable discussion. Solicit questions if needed for topic ideas. You can also share videos from an event or meeting (if permissible).
20) Thank your members, followers, friends, etc for their support

**Comment by visionary920** [comment]
@kdflint Let me know what you think about this list of ideas for SM.

**Comment by kdflint** [comment]
This is an excellent list. Very, very practical!

I'm going to go into Hootsuite and see if there is a good way to organize around these ideas, and the sample calendar that you emailed.

**Comment by kdflint** [comment]
Thinking... let me share our Hootsuite admin password with you and we can start to build some content up.

**Comment by kdflint** [comment]
What's a good deliverable for this? We've got a nice set of ideas for content. We've talked about the goal of  3 posts/week on FB company page. I'm going to pick up my LI activity to 1-2 posts or shares per week on my own timeline, plus a meaty blog post every couple weeks. 

I was thinking next step is to get comfortable with the scheduling tools at Hootsuite, but that work maybe belongs with #9.

**Comment by visionary920** [comment]
Numbers 7, 8 and 9 all work together. We've got the ideas, now it's time to work it. There are more than enough ideas to build up a reserve for maybe even 2 weeks.

**Comment by kdflint** [comment]
I moved these content ideas (also some from email) into a Google Doc

https://docs.google.com/document/d/1ANgObeAK2dDJKVtniK5gUPjWu2JtSLd9oaMUCO5lDRM/edit
